commonLaunchArgs:
  - "--shm-size=1gb"
  - "-it"
  - "--privileged"
  - "--user=root"
  - "--name scigetapp-{port}"
  - "-p {port}:{port}"
  - "-e NEURODESKTOP_VERSION={tag}"
  - "-e CVMFS_DISABLE={cvmfsDisable}"

# Engine-specific configurations
engines:
  # Base configurations for each engine
  podman: &podman_base
    base_cmd: "podman run -d --rm"
    
  docker: &docker_base
    base_cmd: "docker run -d --rm"
    
  tinyrange: &tinyrange_base
    base_cmd: "{tinyrangePath}"


# Platform and engine-specific additional directory configurations
additionalDirConfig:
  tinyrange:
    windows: '--mount-rw "{additionalDir}":/data'
    unix: '--mount-rw "{additionalDir}":/data'
  podman:
    windows: '--volume "{additionalDir}":/data'
    unix: '--volume "{additionalDir}":/data'
  docker:
    windows: '--volume "{additionalDir}":/data'
    unix: '--volume "{additionalDir}":/data'
    
# Launch arguments matrix (engine x platform)
launchArgs:
  podman:
    windows:
      <<: *podman_base
      args:
        - "{base_cmd}"
        - "{commonLaunchArgs}"
        - "-v C://{storageDir}:/{storageDir}"
        - "-v {volume_mount}:/home/jovyan"
        - "--network bridge:ip=10.88.0.10,mac=88:75:56:ef:3e:d6"
        - "{imageRegistry}"
    unix:
      <<: *podman_base
      args:
        - "{base_cmd}"
        - "{commonLaunchArgs}"
        - "-e NB_UID=\"$(id -u)\" -e NB_GID=\"$(id -g)\" -v ~/{storageDir}:/{storageDir}"
        - "-v {volume_mount}:/home/jovyan"
        - "--network bridge:ip=10.88.0.10,mac=88:75:56:ef:3e:d6"
        - "{imageRegistry}"
  
  docker:
    windows:
      <<: *docker_base
      args:
        - "{base_cmd}"
        - "{commonLaunchArgs}"
        - "-v C://{storageDir}:/{storageDir}"
        - "--mount source={volume_mount},target=/home/jovyan --mac-address=88:75:56:ef:3e:d6"
        - "{imageRegistry}"
    unix:
      <<: *docker_base
      args:
        - "{base_cmd}"
        - "{commonLaunchArgs}"
        - "-e NB_UID=\"$(id -u)\" -e NB_GID=\"$(id -g)\" -v ~/{storageDir}:/{storageDir}"
        - "--mount source={volume_mount},target=/home/jovyan --mac-address=88:75:56:ef:3e:d6"
        - "{imageRegistry}"
  
  tinyrange:
    windows:
      <<: *tinyrange_base
      args:
        - "{base_cmd}"
        - "login"
        - "--buildDir {buildDir}"
        - "--oci {imageRegistry}"
        - "--forward {port}"
        - "-m //lib/qemu:user"
        - "--mount-rw C://{storageDir}:/{storageDir}"
        - "--volume neurodeskHome,20480,/home,persist"
        - "--auto-scale"
        - "-E 'chmod 777 /dev/fuse;"
    unix:
      <<: *tinyrange_base
      args:
        - "{base_cmd}"
        - "login"
        - "--buildDir {buildDir}"
        - "--oci {imageRegistry}"
        - "--forward {port}"
        - "-m //lib/qemu:user"
        - "--mount-rw ~/{storageDir}:/{storageDir}"
        - "--volume neurodeskHome,20480,/home,persist"
        - "--auto-scale"
        - "-E 'chmod 777 /dev/fuse;"

# Default server launch arguments (applied if not overridden)
defaultServerArgs:
  - "start.sh jupyter lab"
  - "--ServerApp.password=\"\""
  - "--no-browser"
  - "--expose-app-in-browser"
  - "--ServerApp.token=\"{token}\""
  - "--ServerApp.port={port}"
  - "--LabApp.quit_button=False"